<?php
declare(strict_types=1);

namespace Richbuilds\Orm\Tests\Model\MySql;

use PDO;
use PHPUnit\Framework\TestCase;
use Richbuilds\Orm\Orm;
use Richbuilds\Orm\OrmException;

/**
 *
 */
class MySqlTestBase extends TestCase
{
    protected static Orm $Orm;

    /**
     * This method is called before the first test of this test class is run.
     *
     * @throws OrmException
     */
    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        self::$Orm = new Orm(new PDO('mysql:host=localhost;dbname=orm_test', 'test', 'test'));
    }

}
